all: serialRead getWaveMeterWavelength

serialRead: serialRead.c
	gcc serialRead.c -o serialRead -lwiringPi -Wall

getWaveMeterWavelength: getWaveMeterWavelength.c
	gcc getWaveMeterWavelength.c -o getWaveMeterWavelength -lwiringPi -Wall
